//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMVC.UlipServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCFUlipService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IllustrationGridDtls", Namespace="http://schemas.datacontract.org/2004/07/UlipBL")]
    [System.SerializableAttribute()]
    public partial class IllustrationGridDtls : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmtAvailableforInvestmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BasicPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeathBenefitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FundMgmtChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FundvalueEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FundvalueSurrenderChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MortalityChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyAdminChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremiumAllocationChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PremiumAllocationonAmtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RiderPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurrenderValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopupPremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string err_msgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmtAvailableforInvestment {
            get {
                return this.AmtAvailableforInvestmentField;
            }
            set {
                if ((object.ReferenceEquals(this.AmtAvailableforInvestmentField, value) != true)) {
                    this.AmtAvailableforInvestmentField = value;
                    this.RaisePropertyChanged("AmtAvailableforInvestment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BasicPremium {
            get {
                return this.BasicPremiumField;
            }
            set {
                if ((object.ReferenceEquals(this.BasicPremiumField, value) != true)) {
                    this.BasicPremiumField = value;
                    this.RaisePropertyChanged("BasicPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeathBenefit {
            get {
                return this.DeathBenefitField;
            }
            set {
                if ((object.ReferenceEquals(this.DeathBenefitField, value) != true)) {
                    this.DeathBenefitField = value;
                    this.RaisePropertyChanged("DeathBenefit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FundMgmtCharges {
            get {
                return this.FundMgmtChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.FundMgmtChargesField, value) != true)) {
                    this.FundMgmtChargesField = value;
                    this.RaisePropertyChanged("FundMgmtCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FundvalueEnd {
            get {
                return this.FundvalueEndField;
            }
            set {
                if ((object.ReferenceEquals(this.FundvalueEndField, value) != true)) {
                    this.FundvalueEndField = value;
                    this.RaisePropertyChanged("FundvalueEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FundvalueSurrenderCharges {
            get {
                return this.FundvalueSurrenderChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.FundvalueSurrenderChargesField, value) != true)) {
                    this.FundvalueSurrenderChargesField = value;
                    this.RaisePropertyChanged("FundvalueSurrenderCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MortalityCharges {
            get {
                return this.MortalityChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.MortalityChargesField, value) != true)) {
                    this.MortalityChargesField = value;
                    this.RaisePropertyChanged("MortalityCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyAdminCharges {
            get {
                return this.PolicyAdminChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyAdminChargesField, value) != true)) {
                    this.PolicyAdminChargesField = value;
                    this.RaisePropertyChanged("PolicyAdminCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyYear {
            get {
                return this.PolicyYearField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyYearField, value) != true)) {
                    this.PolicyYearField = value;
                    this.RaisePropertyChanged("PolicyYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Premium {
            get {
                return this.PremiumField;
            }
            set {
                if ((object.ReferenceEquals(this.PremiumField, value) != true)) {
                    this.PremiumField = value;
                    this.RaisePropertyChanged("Premium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremiumAllocationCharges {
            get {
                return this.PremiumAllocationChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.PremiumAllocationChargesField, value) != true)) {
                    this.PremiumAllocationChargesField = value;
                    this.RaisePropertyChanged("PremiumAllocationCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PremiumAllocationonAmt {
            get {
                return this.PremiumAllocationonAmtField;
            }
            set {
                if ((object.ReferenceEquals(this.PremiumAllocationonAmtField, value) != true)) {
                    this.PremiumAllocationonAmtField = value;
                    this.RaisePropertyChanged("PremiumAllocationonAmt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RiderPremium {
            get {
                return this.RiderPremiumField;
            }
            set {
                if ((object.ReferenceEquals(this.RiderPremiumField, value) != true)) {
                    this.RiderPremiumField = value;
                    this.RaisePropertyChanged("RiderPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurrenderValue {
            get {
                return this.SurrenderValueField;
            }
            set {
                if ((object.ReferenceEquals(this.SurrenderValueField, value) != true)) {
                    this.SurrenderValueField = value;
                    this.RaisePropertyChanged("SurrenderValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopCharges {
            get {
                return this.TopChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.TopChargesField, value) != true)) {
                    this.TopChargesField = value;
                    this.RaisePropertyChanged("TopCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopupPremium {
            get {
                return this.TopupPremiumField;
            }
            set {
                if ((object.ReferenceEquals(this.TopupPremiumField, value) != true)) {
                    this.TopupPremiumField = value;
                    this.RaisePropertyChanged("TopupPremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalCharges {
            get {
                return this.TotalChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalChargesField, value) != true)) {
                    this.TotalChargesField = value;
                    this.RaisePropertyChanged("TotalCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string err_msg {
            get {
                return this.err_msgField;
            }
            set {
                if ((object.ReferenceEquals(this.err_msgField, value) != true)) {
                    this.err_msgField = value;
                    this.RaisePropertyChanged("err_msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomeridLOVResult", Namespace="http://schemas.datacontract.org/2004/07/UlipBL")]
    [System.SerializableAttribute()]
    public partial class CustomeridLOVResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_code {
            get {
                return this.customer_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_codeField, value) != true)) {
                    this.customer_codeField = value;
                    this.RaisePropertyChanged("customer_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_name {
            get {
                return this.customer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_nameField, value) != true)) {
                    this.customer_nameField = value;
                    this.RaisePropertyChanged("customer_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicynoLOVResult", Namespace="http://schemas.datacontract.org/2004/07/UlipBL")]
    [System.SerializableAttribute()]
    public partial class PolicynoLOVResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customer_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string policy_effective_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string policy_noField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_code {
            get {
                return this.customer_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_codeField, value) != true)) {
                    this.customer_codeField = value;
                    this.RaisePropertyChanged("customer_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customer_name {
            get {
                return this.customer_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.customer_nameField, value) != true)) {
                    this.customer_nameField = value;
                    this.RaisePropertyChanged("customer_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy_effective_date {
            get {
                return this.policy_effective_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.policy_effective_dateField, value) != true)) {
                    this.policy_effective_dateField = value;
                    this.RaisePropertyChanged("policy_effective_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy_no {
            get {
                return this.policy_noField;
            }
            set {
                if ((object.ReferenceEquals(this.policy_noField, value) != true)) {
                    this.policy_noField = value;
                    this.RaisePropertyChanged("policy_no");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyServicingViewDtls", Namespace="http://schemas.datacontract.org/2004/07/UlipBL")]
    [System.SerializableAttribute()]
    public partial class PolicyServicingViewDtls : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string annual_premiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assured_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string base_sum_insuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string err_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string err_msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_policy_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string policy_start_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string policy_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prem_payment_modeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ref_noField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string annual_premium {
            get {
                return this.annual_premiumField;
            }
            set {
                if ((object.ReferenceEquals(this.annual_premiumField, value) != true)) {
                    this.annual_premiumField = value;
                    this.RaisePropertyChanged("annual_premium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string assured_name {
            get {
                return this.assured_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.assured_nameField, value) != true)) {
                    this.assured_nameField = value;
                    this.RaisePropertyChanged("assured_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string base_sum_insured {
            get {
                return this.base_sum_insuredField;
            }
            set {
                if ((object.ReferenceEquals(this.base_sum_insuredField, value) != true)) {
                    this.base_sum_insuredField = value;
                    this.RaisePropertyChanged("base_sum_insured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string err_code {
            get {
                return this.err_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.err_codeField, value) != true)) {
                    this.err_codeField = value;
                    this.RaisePropertyChanged("err_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string err_msg {
            get {
                return this.err_msgField;
            }
            set {
                if ((object.ReferenceEquals(this.err_msgField, value) != true)) {
                    this.err_msgField = value;
                    this.RaisePropertyChanged("err_msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_policy_no {
            get {
                return this.num_policy_noField;
            }
            set {
                if ((object.ReferenceEquals(this.num_policy_noField, value) != true)) {
                    this.num_policy_noField = value;
                    this.RaisePropertyChanged("num_policy_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy_start_date {
            get {
                return this.policy_start_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.policy_start_dateField, value) != true)) {
                    this.policy_start_dateField = value;
                    this.RaisePropertyChanged("policy_start_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policy_status {
            get {
                return this.policy_statusField;
            }
            set {
                if ((object.ReferenceEquals(this.policy_statusField, value) != true)) {
                    this.policy_statusField = value;
                    this.RaisePropertyChanged("policy_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prem_payment_mode {
            get {
                return this.prem_payment_modeField;
            }
            set {
                if ((object.ReferenceEquals(this.prem_payment_modeField, value) != true)) {
                    this.prem_payment_modeField = value;
                    this.RaisePropertyChanged("prem_payment_mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ref_no {
            get {
                return this.ref_noField;
            }
            set {
                if ((object.ReferenceEquals(this.ref_noField, value) != true)) {
                    this.ref_noField = value;
                    this.RaisePropertyChanged("ref_no");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyServicingProceedDtls", Namespace="http://schemas.datacontract.org/2004/07/UlipBL")]
    [System.SerializableAttribute()]
    public partial class PolicyServicingProceedDtls : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string available_unitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string current_navField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string entry_labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string err_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string err_msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fund_valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string investment_percentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string max_withdrawl_amtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string request_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string available_units {
            get {
                return this.available_unitsField;
            }
            set {
                if ((object.ReferenceEquals(this.available_unitsField, value) != true)) {
                    this.available_unitsField = value;
                    this.RaisePropertyChanged("available_units");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string current_nav {
            get {
                return this.current_navField;
            }
            set {
                if ((object.ReferenceEquals(this.current_navField, value) != true)) {
                    this.current_navField = value;
                    this.RaisePropertyChanged("current_nav");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string entry_label {
            get {
                return this.entry_labelField;
            }
            set {
                if ((object.ReferenceEquals(this.entry_labelField, value) != true)) {
                    this.entry_labelField = value;
                    this.RaisePropertyChanged("entry_label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string err_code {
            get {
                return this.err_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.err_codeField, value) != true)) {
                    this.err_codeField = value;
                    this.RaisePropertyChanged("err_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string err_msg {
            get {
                return this.err_msgField;
            }
            set {
                if ((object.ReferenceEquals(this.err_msgField, value) != true)) {
                    this.err_msgField = value;
                    this.RaisePropertyChanged("err_msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fund_value {
            get {
                return this.fund_valueField;
            }
            set {
                if ((object.ReferenceEquals(this.fund_valueField, value) != true)) {
                    this.fund_valueField = value;
                    this.RaisePropertyChanged("fund_value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string investment_percent {
            get {
                return this.investment_percentField;
            }
            set {
                if ((object.ReferenceEquals(this.investment_percentField, value) != true)) {
                    this.investment_percentField = value;
                    this.RaisePropertyChanged("investment_percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string max_withdrawl_amt {
            get {
                return this.max_withdrawl_amtField;
            }
            set {
                if ((object.ReferenceEquals(this.max_withdrawl_amtField, value) != true)) {
                    this.max_withdrawl_amtField = value;
                    this.RaisePropertyChanged("max_withdrawl_amt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string request_id {
            get {
                return this.request_idField;
            }
            set {
                if ((object.ReferenceEquals(this.request_idField, value) != true)) {
                    this.request_idField = value;
                    this.RaisePropertyChanged("request_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UlipServiceRef.IUlipService")]
    public interface IUlipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetData", ReplyAction="http://tempuri.org/IUlipService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetData", ReplyAction="http://tempuri.org/IUlipService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IUlipService/GetDataUsingDataContractResponse")]
        NewMVC.UlipServiceRef.CompositeType GetDataUsingDataContract(NewMVC.UlipServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IUlipService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<NewMVC.UlipServiceRef.CompositeType> GetDataUsingDataContractAsync(NewMVC.UlipServiceRef.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetIllustrationHeaders", ReplyAction="http://tempuri.org/IUlipService/GetIllustrationHeadersResponse")]
        string[] GetIllustrationHeaders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetIllustrationHeaders", ReplyAction="http://tempuri.org/IUlipService/GetIllustrationHeadersResponse")]
        System.Threading.Tasks.Task<string[]> GetIllustrationHeadersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetIllustrationGridDtls", ReplyAction="http://tempuri.org/IUlipService/GetIllustrationGridDtlsResponse")]
        NewMVC.UlipServiceRef.IllustrationGridDtls[] GetIllustrationGridDtls(string policy_term, string annual_prem, string sum_assurred, string topup_prem, string rider_prem, string typeof_request, string illustration_no, string annual_interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetIllustrationGridDtls", ReplyAction="http://tempuri.org/IUlipService/GetIllustrationGridDtlsResponse")]
        System.Threading.Tasks.Task<NewMVC.UlipServiceRef.IllustrationGridDtls[]> GetIllustrationGridDtlsAsync(string policy_term, string annual_prem, string sum_assurred, string topup_prem, string rider_prem, string typeof_request, string illustration_no, string annual_interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/SaveIllustrationDtls", ReplyAction="http://tempuri.org/IUlipService/SaveIllustrationDtlsResponse")]
        string[] SaveIllustrationDtls(string customer_id, string customer_name, string product_code, string product_name, string entry_age, string policy_term, string gender, string times_sa, string annual_prem, string sum_assurred, string topup_prem, string rider_prem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/SaveIllustrationDtls", ReplyAction="http://tempuri.org/IUlipService/SaveIllustrationDtlsResponse")]
        System.Threading.Tasks.Task<string[]> SaveIllustrationDtlsAsync(string customer_id, string customer_name, string product_code, string product_name, string entry_age, string policy_term, string gender, string times_sa, string annual_prem, string sum_assurred, string topup_prem, string rider_prem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/CustomerIdLOVPopulate", ReplyAction="http://tempuri.org/IUlipService/CustomerIdLOVPopulateResponse")]
        NewMVC.UlipServiceRef.CustomeridLOVResult[] CustomerIdLOVPopulate(string param1, string param2, string param3, string param4, string param5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/CustomerIdLOVPopulate", ReplyAction="http://tempuri.org/IUlipService/CustomerIdLOVPopulateResponse")]
        System.Threading.Tasks.Task<NewMVC.UlipServiceRef.CustomeridLOVResult[]> CustomerIdLOVPopulateAsync(string param1, string param2, string param3, string param4, string param5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/ExportPdf", ReplyAction="http://tempuri.org/IUlipService/ExportPdfResponse")]
        string ExportPdf(string proposer_name, string product_name, string entry_age, string gender, string policy_term, string annual_prem, string base_suminsured_percent, string base_suminsured, string rider_suminsured_percent, string rider_suminsured, string topup_prem, string[] list_rates, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid1_result, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid2_result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/ExportPdf", ReplyAction="http://tempuri.org/IUlipService/ExportPdfResponse")]
        System.Threading.Tasks.Task<string> ExportPdfAsync(string proposer_name, string product_name, string entry_age, string gender, string policy_term, string annual_prem, string base_suminsured_percent, string base_suminsured, string rider_suminsured_percent, string rider_suminsured, string topup_prem, string[] list_rates, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid1_result, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid2_result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/PolicyNoLOVPopulate", ReplyAction="http://tempuri.org/IUlipService/PolicyNoLOVPopulateResponse")]
        NewMVC.UlipServiceRef.PolicynoLOVResult[] PolicyNoLOVPopulate(string param1, string param2, string param3, string param4, string param5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/PolicyNoLOVPopulate", ReplyAction="http://tempuri.org/IUlipService/PolicyNoLOVPopulateResponse")]
        System.Threading.Tasks.Task<NewMVC.UlipServiceRef.PolicynoLOVResult[]> PolicyNoLOVPopulateAsync(string param1, string param2, string param3, string param4, string param5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetViewDtls", ReplyAction="http://tempuri.org/IUlipService/GetViewDtlsResponse")]
        NewMVC.UlipServiceRef.PolicyServicingViewDtls GetViewDtls(string policy_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetViewDtls", ReplyAction="http://tempuri.org/IUlipService/GetViewDtlsResponse")]
        System.Threading.Tasks.Task<NewMVC.UlipServiceRef.PolicyServicingViewDtls> GetViewDtlsAsync(string policy_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetProceedDtls", ReplyAction="http://tempuri.org/IUlipService/GetProceedDtlsResponse")]
        NewMVC.UlipServiceRef.PolicyServicingProceedDtls[] GetProceedDtls(string txt_policy_no, string ref_no, string num_policy_no, string new_equity_percent, string new_balance_percent, string new_debit_percent, string topup_amt, string txt_request_type, string txt_process_name, string policy_status, string policy_eff_fromdate, string actual_withdrawl_amt, string prem_payment_mode, string max_withdrawl_amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUlipService/GetProceedDtls", ReplyAction="http://tempuri.org/IUlipService/GetProceedDtlsResponse")]
        System.Threading.Tasks.Task<NewMVC.UlipServiceRef.PolicyServicingProceedDtls[]> GetProceedDtlsAsync(string txt_policy_no, string ref_no, string num_policy_no, string new_equity_percent, string new_balance_percent, string new_debit_percent, string topup_amt, string txt_request_type, string txt_process_name, string policy_status, string policy_eff_fromdate, string actual_withdrawl_amt, string prem_payment_mode, string max_withdrawl_amt);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUlipServiceChannel : NewMVC.UlipServiceRef.IUlipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UlipServiceClient : System.ServiceModel.ClientBase<NewMVC.UlipServiceRef.IUlipService>, NewMVC.UlipServiceRef.IUlipService {
        
        public UlipServiceClient() {
        }
        
        public UlipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UlipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UlipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UlipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public NewMVC.UlipServiceRef.CompositeType GetDataUsingDataContract(NewMVC.UlipServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<NewMVC.UlipServiceRef.CompositeType> GetDataUsingDataContractAsync(NewMVC.UlipServiceRef.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string[] GetIllustrationHeaders() {
            return base.Channel.GetIllustrationHeaders();
        }
        
        public System.Threading.Tasks.Task<string[]> GetIllustrationHeadersAsync() {
            return base.Channel.GetIllustrationHeadersAsync();
        }
        
        public NewMVC.UlipServiceRef.IllustrationGridDtls[] GetIllustrationGridDtls(string policy_term, string annual_prem, string sum_assurred, string topup_prem, string rider_prem, string typeof_request, string illustration_no, string annual_interest) {
            return base.Channel.GetIllustrationGridDtls(policy_term, annual_prem, sum_assurred, topup_prem, rider_prem, typeof_request, illustration_no, annual_interest);
        }
        
        public System.Threading.Tasks.Task<NewMVC.UlipServiceRef.IllustrationGridDtls[]> GetIllustrationGridDtlsAsync(string policy_term, string annual_prem, string sum_assurred, string topup_prem, string rider_prem, string typeof_request, string illustration_no, string annual_interest) {
            return base.Channel.GetIllustrationGridDtlsAsync(policy_term, annual_prem, sum_assurred, topup_prem, rider_prem, typeof_request, illustration_no, annual_interest);
        }
        
        public string[] SaveIllustrationDtls(string customer_id, string customer_name, string product_code, string product_name, string entry_age, string policy_term, string gender, string times_sa, string annual_prem, string sum_assurred, string topup_prem, string rider_prem) {
            return base.Channel.SaveIllustrationDtls(customer_id, customer_name, product_code, product_name, entry_age, policy_term, gender, times_sa, annual_prem, sum_assurred, topup_prem, rider_prem);
        }
        
        public System.Threading.Tasks.Task<string[]> SaveIllustrationDtlsAsync(string customer_id, string customer_name, string product_code, string product_name, string entry_age, string policy_term, string gender, string times_sa, string annual_prem, string sum_assurred, string topup_prem, string rider_prem) {
            return base.Channel.SaveIllustrationDtlsAsync(customer_id, customer_name, product_code, product_name, entry_age, policy_term, gender, times_sa, annual_prem, sum_assurred, topup_prem, rider_prem);
        }
        
        public NewMVC.UlipServiceRef.CustomeridLOVResult[] CustomerIdLOVPopulate(string param1, string param2, string param3, string param4, string param5) {
            return base.Channel.CustomerIdLOVPopulate(param1, param2, param3, param4, param5);
        }
        
        public System.Threading.Tasks.Task<NewMVC.UlipServiceRef.CustomeridLOVResult[]> CustomerIdLOVPopulateAsync(string param1, string param2, string param3, string param4, string param5) {
            return base.Channel.CustomerIdLOVPopulateAsync(param1, param2, param3, param4, param5);
        }
        
        public string ExportPdf(string proposer_name, string product_name, string entry_age, string gender, string policy_term, string annual_prem, string base_suminsured_percent, string base_suminsured, string rider_suminsured_percent, string rider_suminsured, string topup_prem, string[] list_rates, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid1_result, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid2_result) {
            return base.Channel.ExportPdf(proposer_name, product_name, entry_age, gender, policy_term, annual_prem, base_suminsured_percent, base_suminsured, rider_suminsured_percent, rider_suminsured, topup_prem, list_rates, grid1_result, grid2_result);
        }
        
        public System.Threading.Tasks.Task<string> ExportPdfAsync(string proposer_name, string product_name, string entry_age, string gender, string policy_term, string annual_prem, string base_suminsured_percent, string base_suminsured, string rider_suminsured_percent, string rider_suminsured, string topup_prem, string[] list_rates, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid1_result, NewMVC.UlipServiceRef.IllustrationGridDtls[] grid2_result) {
            return base.Channel.ExportPdfAsync(proposer_name, product_name, entry_age, gender, policy_term, annual_prem, base_suminsured_percent, base_suminsured, rider_suminsured_percent, rider_suminsured, topup_prem, list_rates, grid1_result, grid2_result);
        }
        
        public NewMVC.UlipServiceRef.PolicynoLOVResult[] PolicyNoLOVPopulate(string param1, string param2, string param3, string param4, string param5) {
            return base.Channel.PolicyNoLOVPopulate(param1, param2, param3, param4, param5);
        }
        
        public System.Threading.Tasks.Task<NewMVC.UlipServiceRef.PolicynoLOVResult[]> PolicyNoLOVPopulateAsync(string param1, string param2, string param3, string param4, string param5) {
            return base.Channel.PolicyNoLOVPopulateAsync(param1, param2, param3, param4, param5);
        }
        
        public NewMVC.UlipServiceRef.PolicyServicingViewDtls GetViewDtls(string policy_no) {
            return base.Channel.GetViewDtls(policy_no);
        }
        
        public System.Threading.Tasks.Task<NewMVC.UlipServiceRef.PolicyServicingViewDtls> GetViewDtlsAsync(string policy_no) {
            return base.Channel.GetViewDtlsAsync(policy_no);
        }
        
        public NewMVC.UlipServiceRef.PolicyServicingProceedDtls[] GetProceedDtls(string txt_policy_no, string ref_no, string num_policy_no, string new_equity_percent, string new_balance_percent, string new_debit_percent, string topup_amt, string txt_request_type, string txt_process_name, string policy_status, string policy_eff_fromdate, string actual_withdrawl_amt, string prem_payment_mode, string max_withdrawl_amt) {
            return base.Channel.GetProceedDtls(txt_policy_no, ref_no, num_policy_no, new_equity_percent, new_balance_percent, new_debit_percent, topup_amt, txt_request_type, txt_process_name, policy_status, policy_eff_fromdate, actual_withdrawl_amt, prem_payment_mode, max_withdrawl_amt);
        }
        
        public System.Threading.Tasks.Task<NewMVC.UlipServiceRef.PolicyServicingProceedDtls[]> GetProceedDtlsAsync(string txt_policy_no, string ref_no, string num_policy_no, string new_equity_percent, string new_balance_percent, string new_debit_percent, string topup_amt, string txt_request_type, string txt_process_name, string policy_status, string policy_eff_fromdate, string actual_withdrawl_amt, string prem_payment_mode, string max_withdrawl_amt) {
            return base.Channel.GetProceedDtlsAsync(txt_policy_no, ref_no, num_policy_no, new_equity_percent, new_balance_percent, new_debit_percent, topup_amt, txt_request_type, txt_process_name, policy_status, policy_eff_fromdate, actual_withdrawl_amt, prem_payment_mode, max_withdrawl_amt);
        }
    }
}
